---
version: "2.1"
services:
  cloud9:
    image: ghcr.io/linuxserver/cloud9
    container_name: cloud9
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - USERNAME=cloud9 #optional
      - PASSWORD=cloud9 #optional
    volumes:
      - /home/ubuntu/code:/code
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/abc/.ssh
    ports:
      - 8000:8000
    restart: unless-stopped

    # required commands after set up - inside Cloud9 IDE terminal (TODO move to after start script)
    # sudo apt update
    # sudo apt upgrade
    # sudo apt install ssh
    # eval "$(ssh-agent -s)"
    # ssh-add /abc/.ssh/id_ed25519